AWSTemplateFormatVersion: '2020-11-13'
Description: "Create CodeBuild project with required IAM/SG/SSM/CW Logs configuration and S3/DynamoDB for Terraform"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Top-level environment configuration"
        Parameters:
          - ProjectName
          - Environment
      -
        Label:
          default: "VPC configuration for CodeBuild"
        Parameters:
          - VpcID
          - PrivateSubnetIDs
      -
        Label:
          default: "IAM configuration"
        Parameters:
          - IAMCodeBuildPoliciesARNs
      -
        Label:
          default: "Git repository configuration (e.g. Bitbucket)"
        Parameters:
          - ConfigRepoURL
          - GitSSHPrivateKey
          - GitBranch
          - DeploymentDirPath

Parameters:
  ProjectName:
    Description: String that will be used as basis for naming S3 bucket, CB project, etc.
    Type: String
    Default: aws-challenge
  Environment:
    Description: Environmnet type from dev, int, prod
    Type: String
    Default: 'dev'
  VpcID:
    Type: AWS::EC2::VPC::Id
    Description: VPC in which CB project will run
  PrivateSubnetIDs:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnets in which CB will run (only private are supported)
  IAMCodeBuildPoliciesARNs:
    Description: List of IAM policy ARNs to be attached to CodeBuild role (comma separated string, no spaces)
    Default: 'arn:aws:iam::aws:policy/AdministratorAccess'
    Type: String
  ConfigRepoURL:
    Description: (Optional)Full ssh URL to configuration repository (starting with ssh://)
    Type: String
    Default: 'somerepo.github.com'
  GitSSHPrivateKey:
    NoEcho: 'true'
    Description: Private SSH key to access repositories (read-only is sufficient)
    Type: String
  GitBranch:
    Description: Git branch of config repo to deploy
    Type: String
    Default: master
  DeploymentDirPath:
    Description: List of ordered space separated Paths in repository to run terraform at
    Type: String
    Default: "infrastructure assets"
  TerraformVersion:
    Description: Terraform version
    Type: String
    Default: '0.12.24'
Resources:
  ####################################
  # PARAMETERS IN SSM PARAMETER STORE:
  ####################################

  
  ####################################
  # IAM:
  ####################################
  

  ####################################
  # VPC resources:
  ####################################
  


  ####################################
  # CloudWatch Logs
  ####################################
  

  ####################################
  # CodeBuild:
  ####################################
  
  ####################################
  # Terraform state:
  ####################################
  

####################################
# PARAMETERS IN SSM PARAMETER STORE:
####################################


####################################
# OUTPUTS:
####################################
Outputs:
  CodeBuildURL:
    Description: URL to CodeBuild project that will run Terraform
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/codesuite/codebuild/projects/${CodeBuildProject}"